[profile.default]
solc-version = "0.8.17"
optimizer = true
optimizer_runs = 10_000
src = 'src'
out = 'out'
libs = ['lib', 'node_modules']
remappings = [
    'eth-gas-reporter/=node_modules/eth-gas-reporter/',
    'hardhat/=node_modules/hardhat/',
    'solmate/=node_modules/solmate/',
    '@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/',
]
